name: ci

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - name: Check out source code
        uses: actions/checkout@v3
      - run: echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"
      - run: make deps
      - run: make verify_swagger_nochange
      - run: make ci
      - run: make benchmark
      # - uses: codecov/codecov-action@v2
  ui_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Check out source code
        uses: actions/checkout@v3
      - run: cd browser/flagr-ui && npm install
      - run: cd browser/flagr-ui && npm run lint
  integration_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3
      - run: cd integration_tests && make build-image
      - run: cd integration_tests && make down
      - run: cd integration_tests && make up
      - run: cd integration_tests && make test
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        shell: bash
      - name: Check workflow files
        run: ${{ steps.get_actionlint.outputs.executable }} -color
        shell: bash
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: tradeshift/actions-docker@v1
        with:
          repository: 063399264027.dkr.ecr.eu-west-1.amazonaws.com/tradeshift-base/openflagr
          platform: linux/amd64
          push: true
          aws-access-key-id: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
